"""opencode Teacher - uses opencode (this AI) to teach Ickle.

Since opencode is an interactive AI assistant, this adapter works in
interactive mode - it presents prompts to opencode via the chat interface,
and opencode responds with improved answers, feedback, and training data.

Three modes:
  curriculum  - Generate a set of training prompts for a topic
  teach-turn  - Submit a prompt to Ickle, have opencode critique & improve
  batch-sft   - Generate User:/Ickle: SFT pairs for a topic interactively
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from src.teacher_base import TeacherBase, extract_json


class OpencodeTeacher(TeacherBase):
    """Teacher adapter for opencode (this AI assistant).

    Since opencode responds via chat, this operates in interactive mode:
    prompts are printed to stdout and answers are read from stdin.
    Supports non-interactive file-based mode for batch operations.
    """

    def __init__(self, teacher_name: str = "opencode", interactive: bool = True):
        super().__init__(teacher_name=teacher_name)
        self.interactive = interactive

    def check_connection(self) -> dict[str, Any]:
        return {"ok": True, "teacher": self.teacher_name}

    def generate_text(
        self,
        prompt: str,
        *,
        system: str = "",
        temperature: float = 0.3,
        max_tokens: int = 2000,
    ) -> str:
        print(f"\n{'='*60}")
        print(f"[opencode-teacher] I need your expertise on this topic:")
        print(f"{'='*60}")
        if system:
            print(f"\nContext: {system}")
        print(f"\nPrompt:\n{prompt}")
        print(f"{'='*60}")
        print(f"Write your answer below (then press Enter, then Ctrl+D or type '---END---' on its own line):")
        print(f"{'='*60}")

        lines = []
        try:
            while True:
                line = input()
                if line.strip() == "---END---":
                    break
                lines.append(line)
        except (EOFError, KeyboardInterrupt):
            pass

        return "\n".join(lines).strip()

    def teach_turn(
        self,
        prompt: str,
        ickle_answer: str = "",
        *,
        tags: list[str] | None = None,
        retries: int = 2,
    ) -> dict[str, Any]:
        print(f"\n{'='*60}")
        print(f"[opencode-teacher] Teach Turn - please review and improve:")
        print(f"{'='*60}")
        print(f"\nStudent prompt: {prompt}")
        print(f"\nIckle's current answer: {ickle_answer or '(no answer yet)'}")
        print(f"\nPlease provide:")
        print(f"  1. improved_answer - A clear, accurate, well-formatted answer")
        print(f"  2. teacher_feedback - 1-2 sentences explaining what was improved")
        print(f"  3. score - A quality score from 0.0 to 1.0")
        print(f"\nEnter as JSON (or type '---SKIP---' to skip):")
        print(f"{'='*60}")

        lines = []
        try:
            while True:
                line = input()
                if line.strip() == "---SKIP---":
                    raise RuntimeError("Skipped by user")
                if line.strip() == "---END---":
                    break
                lines.append(line)
        except (EOFError, KeyboardInterrupt):
            pass

        raw = "\n".join(lines).strip()
        result = extract_json(raw) if raw else None
        if not result:
            result = {
                "improved_answer": raw or prompt,
                "teacher_feedback": "Generated by opencode teacher",
                "score": 0.7,
            }

        return {
            "improved_answer": str(result.get("improved_answer", raw)).strip(),
            "teacher_feedback": str(result.get("teacher_feedback", "Generated by opencode teacher")).strip(),
            "score": max(0.0, min(1.0, float(result.get("score", 0.7)))),
            "prompt": prompt,
            "ickle_answer": ickle_answer,
            "tags": tags or [],
            "source_model": self.teacher_name,
        }

    def batch_sft(
        self,
        topic: str,
        count: int = 6,
        *,
        tags: list[str] | None = None,
        retries: int = 2,
    ) -> list[dict[str, Any]]:
        print(f"\n{'='*60}")
        print(f"[opencode-teacher] Generate {count} SFT pairs for topic: {topic}")
        print(f"{'='*60}")
        print(f"For each pair, provide:")
        print(f"  - prompt (the user question)")
        print(f"  - answer (the ideal Ickle response)")
        print(f"  - tags (optional, comma-separated)")
        print(f"\nEnter pairs one by one. Type '---SKIP---' to finish early.")
        print(f"{'='*60}")

        pairs: list[dict[str, Any]] = []
        for i in range(count):
            print(f"\n--- Pair {i+1}/{count} ---")
            print(f"Enter prompt (or '---SKIP---' to finish): ", end="")
            try:
                prompt = input().strip()
            except (EOFError, KeyboardInterrupt):
                break
            if not prompt or prompt == "---SKIP---":
                break
            print(f"Enter answer: ", end="")
            try:
                answer = input().strip()
            except (EOFError, KeyboardInterrupt):
                break
            if not answer:
                continue
            print(f"Enter tags (comma-separated, optional): ", end="")
            try:
                item_tags = [t.strip() for t in input().strip().split(",") if t.strip()]
            except (EOFError, KeyboardInterrupt):
                item_tags = []

            pairs.append({
                "prompt": prompt,
                "ickle_answer": "",
                "improved_answer": answer,
                "teacher_feedback": f"Generated {topic} training example by opencode",
                "score": 0.8,
                "tags": item_tags or tags or [topic],
                "source_model": self.teacher_name,
            })

        return pairs


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="opencode Teacher - use opencode (this AI) to teach Ickle"
    )
    parser.add_argument("mode", choices=["check", "curriculum", "teach", "batch-sft", "submit"])
    parser.add_argument("--teacher-name", default="opencode", help="Name recorded as source_model")
    parser.add_argument("--topic", default="", help="Topic for curriculum or batch-sft")
    parser.add_argument("--prompt", default="", help="Prompt for teach-turn mode")
    parser.add_argument("--ickle-answer", default="", help="Ickle's current answer (for teach mode)")
    parser.add_argument("--count", type=int, default=8, help="Number of items to generate")
    parser.add_argument("--tags", default="", help="Comma-separated tags")
    parser.add_argument("--store-dir", default="data/teacher", help="Teacher store directory")
    parser.add_argument("--api-url", default="", help="Submit via HTTP API (e.g. http://localhost:8788)")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--non-interactive", action="store_true", help="Use file-based input instead of interactive prompts")

    args = parser.parse_args()
    teacher = OpencodeTeacher(teacher_name=args.teacher_name, interactive=not args.non_interactive)
    tag_list = [t.strip() for t in (args.tags or "").split(",") if t.strip()]

    if args.mode == "check":
        result = teacher.check_connection()
        if args.json:
            print(json.dumps(result, ensure_ascii=False))
        else:
            print("opencode teacher is connected and ready.")
        return

    if args.mode == "curriculum":
        if not args.topic:
            print("Error: --topic required for curriculum mode", file=sys.stderr)
            sys.exit(1)
        print(f"Generating {args.count} curriculum prompts for '{args.topic}'...")
        prompts = teacher.generate_curriculum(args.topic, count=args.count, tags=tag_list)
        if args.json:
            print(json.dumps({"topic": args.topic, "prompts": prompts}, ensure_ascii=False))
        else:
            for i, p in enumerate(prompts, 1):
                print(f"  {i}. {p}")
        return

    if args.mode == "teach":
        if not args.prompt:
            print("Error: --prompt required for teach mode", file=sys.stderr)
            sys.exit(1)
        print(f"Teaching turn for: {args.prompt[:80]}...")
        turn = teacher.teach_turn(args.prompt, ickle_answer=args.ickle_answer, tags=tag_list)
        if args.json:
            print(json.dumps(turn, ensure_ascii=False))
        else:
            print(f"Score: {turn['score']}")
            print(f"Feedback: {turn['teacher_feedback']}")
            print(f"Answer: {turn['improved_answer'][:500]}")
        return

    if args.mode == "batch-sft":
        if not args.topic:
            print("Error: --topic required for batch-sft mode", file=sys.stderr)
            sys.exit(1)
        print(f"Generating {args.count} SFT pairs for '{args.topic}'...")
        pairs = teacher.batch_sft(args.topic, count=args.count, tags=tag_list)
        if args.json:
            print(json.dumps({"topic": args.topic, "pairs": pairs}, ensure_ascii=False))
        else:
            for i, pair in enumerate(pairs, 1):
                print(f"\n--- Pair {i} ---")
                print(f"Q: {pair['prompt']}")
                print(f"A: {pair['improved_answer'][:200]}")
        return

    if args.mode == "submit":
        if not args.prompt:
            print("Error: --prompt required for submit mode", file=sys.stderr)
            sys.exit(1)
        prompt_path = Path(args.prompt)
        if prompt_path.exists():
            with prompt_path.open(encoding="utf-8") as f:
                turns = json.load(f)
            if not isinstance(turns, list):
                print("Error: JSON file must contain a list of turn objects", file=sys.stderr)
                sys.exit(1)
        else:
            try:
                turns = json.loads(args.prompt)
                if not isinstance(turns, list):
                    turns = [turns]
            except json.JSONDecodeError:
                print("Error: --prompt must be a JSON file path or valid JSON array", file=sys.stderr)
                sys.exit(1)

        if args.api_url:
            print(f"Submitting {len(turns)} turns via API at {args.api_url}...")
            result = teacher.submit_via_api(turns, topic=args.topic or "opencode_teaching", api_url=args.api_url)
        else:
            print(f"Submitting {len(turns)} turns to local store...")
            result = teacher.submit_to_store(turns, topic=args.topic or "opencode_teaching", store_dir=args.store_dir)

        if args.json:
            print(json.dumps(result, ensure_ascii=False))
        else:
            print(f"Session {result['session_id']}: {result['turns_submitted']} turns submitted")
        return


if __name__ == "__main__":
    main()
